version: '3'
services:
  btc:
    build: ./bitcoind
    image: bitcoind:latest
    container_name: btc
    restart: always
    ports:
      - "8333:8333"
      - "28333:28333"
      - "28332:28332"
    volumes:
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
      - /home/nitram/.bitcoin/:/root/.bitcoin/ # uncomment/adjust if you have all blocks already
  lnd:
    build: ./lnd
    image: lnd:latest
    container_name: lnd
    restart: always
    ports:
      - "9735:9735"
    volumes:
      - ./lnd/lnd.conf:/root/.lnd/lnd.conf:ro
      - /home/nitram/.lnd:/root/.lnd
